package com.servicios.admin;

import com.servicios.bean.UsuarioBean;

public class AdminDashboard extends javax.swing.JFrame {

    private UsuarioBean usuario;

    /**
     * Creates new form Dasboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        adminusuarios = new javax.swing.JMenu();
        subusuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        subadmempresa = new javax.swing.JMenuItem();
        adminservicios = new javax.swing.JMenu();
        subadmservicio = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        subadmmanteni = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        adminusuarios.setText("Usuario");

        subusuario.setText("Usuarios");
        subusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subusuarioActionPerformed(evt);
            }
        });
        adminusuarios.add(subusuario);

        jMenuBar1.add(adminusuarios);

        jMenu2.setText("Empresa");

        subadmempresa.setText("Adm. Empresa");
        subadmempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subadmempresaActionPerformed(evt);
            }
        });
        jMenu2.add(subadmempresa);

        jMenuBar1.add(jMenu2);

        adminservicios.setText("Servicio");

        subadmservicio.setText("Adm. Servicios");
        subadmservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subadmservicioActionPerformed(evt);
            }
        });
        adminservicios.add(subadmservicio);

        jMenuBar1.add(adminservicios);

        jMenu4.setText("Mantenimiento");

        subadmmanteni.setText("Adm. Mantenimiento");
        subadmmanteni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subadmmanteniActionPerformed(evt);
            }
        });
        jMenu4.add(subadmmanteni);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subadmservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subadmservicioActionPerformed
        AdminServicio admin = new AdminServicio();
        admin.setVisible(true);
    }//GEN-LAST:event_subadmservicioActionPerformed

    private void subadmempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subadmempresaActionPerformed
        AdminEmpresa admin = new AdminEmpresa();
        admin.setVisible(true);
    }//GEN-LAST:event_subadmempresaActionPerformed

    private void subusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subusuarioActionPerformed
        AdminUsuario admin = new AdminUsuario();
        admin.setVisible(true);
    }//GEN-LAST:event_subusuarioActionPerformed

    private void subadmmanteniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subadmmanteniActionPerformed
        AdminMantenimiento admin = new AdminMantenimiento();
        admin.setVisible(true);
    }//GEN-LAST:event_subadmmanteniActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminservicios;
    private javax.swing.JMenu adminusuarios;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem subadmempresa;
    private javax.swing.JMenuItem subadmmanteni;
    private javax.swing.JMenuItem subadmservicio;
    private javax.swing.JMenuItem subusuario;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the usuario
     */
    public UsuarioBean getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(UsuarioBean usuario) {
        this.usuario = usuario;
    }
}
