package com.servicios.admin;

import com.servicios.bean.ComboItemBean;
import com.servicios.bean.MantenimientoBean;
import com.servicios.dao.EmpresaDAO;
import com.servicios.dao.MantenimientoDAO;
import com.servicios.dao.ServicioDAO;
import com.servicios.usuario.Mantenimiento;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class AdminMantenimiento extends javax.swing.JFrame {

    private int servid;
    private ArrayList<ComboItemBean> empresas;
    private ArrayList<ComboItemBean> servicios;

    /**
     * Creates new form Adminservicios
     */
    public AdminMantenimiento() {
        initComponents();
    }

    public void limpiarCampos() {
        cbmempresa.setSelectedIndex(0);
        cbmservicio.setSelectedIndex(0);
        cbmmnto.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnaprobar = new javax.swing.JButton();
        cbmempresa = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbmservicio = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cbmmnto = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantenimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnaprobar.setText("Aprobar");
        btnaprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaprobarActionPerformed(evt);
            }
        });

        jLabel6.setText("Empresa:");

        jLabel7.setText("Servicio:");

        jLabel8.setText("Mantenimiento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnaprobar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbmmnto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbmservicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbmempresa, 0, 391, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbmempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbmservicio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbmmnto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnaprobar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            setLocationRelativeTo(null);
            EmpresaDAO empresaDAO = new EmpresaDAO();
            cbmempresa.addItem(new ComboItemBean(0, "Seleccione..."));
            cbmservicio.addItem(new ComboItemBean(0, "Seleccione..."));
            cbmmnto.addItem(new ComboItemBean(0, "Seleccione..."));
            empresas = empresaDAO.getComboEmpresas();
            for (ComboItemBean empresa : empresas) {
                cbmempresa.addItem(empresa);
            }

            //Listener de empresas
            cbmempresa.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent e) {
                    if (e.getStateChange() == ItemEvent.SELECTED) {
                        cbmservicio.removeAllItems();
                        cbmservicio.addItem(new ComboItemBean(0, "Seleccione..."));
                        try {
                            if (cbmempresa.getSelectedIndex() > 0) {
                                ComboItemBean empresa = (ComboItemBean) cbmempresa.getSelectedItem();
                                ServicioDAO servicioDAO = new ServicioDAO();
                                servicios = servicioDAO.getServiciosEmpresa(empresa.getValue());
                                for (ComboItemBean servicio : servicios) {
                                    cbmservicio.addItem(servicio);
                                }
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Mantenimiento.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }
            });

            //Listener de servicios
            cbmservicio.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent e) {
                    if (e.getStateChange() == ItemEvent.SELECTED) {
                        cbmmnto.removeAllItems();
                        cbmmnto.addItem(new ComboItemBean(0, "Seleccione..."));
                        try {
                            if (cbmservicio.getSelectedIndex() > 0) {
                                ComboItemBean empresa = (ComboItemBean) cbmempresa.getSelectedItem();
                                ComboItemBean servicio = (ComboItemBean) cbmservicio.getSelectedItem();
                                MantenimientoDAO dao = new MantenimientoDAO();
                                MantenimientoBean mantenimiento = new MantenimientoBean();
                                mantenimiento.setEmprid(empresa.getValue());
                                mantenimiento.setServid(servicio.getValue());
                                ArrayList<ComboItemBean> mantenimientos = dao.getMantenimientos(mantenimiento);
                                for (ComboItemBean mnto : mantenimientos) {
                                    cbmmnto.addItem(mnto);
                                }
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Mantenimiento.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }
            });

        } catch (SQLException ex) {
            Logger.getLogger(AdminMantenimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnaprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaprobarActionPerformed
        try {
            if (cbmempresa.getSelectedIndex() > 0 && cbmservicio.getSelectedIndex() > 0 && cbmmnto.getSelectedIndex() > 0) {
                MantenimientoDAO dao = new MantenimientoDAO();
                ComboItemBean empresa = (ComboItemBean) cbmempresa.getSelectedItem();
                ComboItemBean servicio = (ComboItemBean) cbmservicio.getSelectedItem();
                ComboItemBean mnto = (ComboItemBean) cbmmnto.getSelectedItem();

                MantenimientoBean mant = new MantenimientoBean();
                mant.setEmprid(empresa.getValue());
                mant.setServid(servicio.getValue());
                mant.setMantid(mnto.getValue());
                dao.aprobarMantenimiento(mant);

                limpiarCampos();
                JOptionPane.showMessageDialog(null, "El mantenimiento fue aprobado");
            } else {
                JOptionPane.showMessageDialog(null, "Los siguientes campos son obligatorios:\n\n"
                        + "* Empresa\n"
                        + "* Servicio\n"
                        + "* Mantenimiento\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminMantenimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaprobarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaprobar;
    private javax.swing.JComboBox cbmempresa;
    private javax.swing.JComboBox cbmmnto;
    private javax.swing.JComboBox cbmservicio;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the servid
     */
    public int getServid() {
        return servid;
    }

    /**
     * @param servid the servid to set
     */
    public void setServid(int servid) {
        this.servid = servid;
    }
}
