package com.servicios.usuario;

import com.servicios.bean.UsuarioBean;

public class Dashboard extends javax.swing.JFrame {

    private UsuarioBean usuario;
    
    /**
     * Creates new form Dash
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        verservicio = new javax.swing.JMenu();
        subverservicio = new javax.swing.JMenuItem();
        subdejarservicio = new javax.swing.JMenuItem();
        submantenimiento = new javax.swing.JMenuItem();
        pagos = new javax.swing.JMenu();
        subhistorialpagos = new javax.swing.JMenuItem();
        subhacerpago = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        verservicio.setText("Servicios");

        subverservicio.setText("Ver Servicios");
        subverservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subverservicioActionPerformed(evt);
            }
        });
        verservicio.add(subverservicio);

        subdejarservicio.setText("Prescindir servicio");
        subdejarservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subdejarservicioActionPerformed(evt);
            }
        });
        verservicio.add(subdejarservicio);

        submantenimiento.setText("Mantenimiento");
        submantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submantenimientoActionPerformed(evt);
            }
        });
        verservicio.add(submantenimiento);

        jMenuBar1.add(verservicio);

        pagos.setText("Pagos");

        subhistorialpagos.setText("Historial de pagos");
        subhistorialpagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subhistorialpagosActionPerformed(evt);
            }
        });
        pagos.add(subhistorialpagos);

        subhacerpago.setText("Realizar pagos");
        subhacerpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subhacerpagoActionPerformed(evt);
            }
        });
        pagos.add(subhacerpago);

        jMenuBar1.add(pagos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subverservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subverservicioActionPerformed
        Servicios verser = new Servicios();
        verser.setUsuario(usuario);
        verser.setVisible(true);
    }//GEN-LAST:event_subverservicioActionPerformed

    private void subdejarservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subdejarservicioActionPerformed
        Precindir precindir = new Precindir();
        precindir.setUsuario(usuario);
        precindir.setVisible(true);        
    }//GEN-LAST:event_subdejarservicioActionPerformed

    private void submantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submantenimientoActionPerformed
        Mantenimiento mant = new Mantenimiento();
        mant.setUsuario(usuario);
        mant.setVisible(true);
    }//GEN-LAST:event_submantenimientoActionPerformed

    private void subhistorialpagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subhistorialpagosActionPerformed
        HistoricoPagos histo = new HistoricoPagos();
        histo.setUsuario(usuario);
        histo.setVisible(true);
    }//GEN-LAST:event_subhistorialpagosActionPerformed

    private void subhacerpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subhacerpagoActionPerformed
        RealizarPagos pagos = new RealizarPagos();
        pagos.setUsuario(usuario);
        pagos.setVisible(true);        
    }//GEN-LAST:event_subhacerpagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu pagos;
    private javax.swing.JMenuItem subdejarservicio;
    private javax.swing.JMenuItem subhacerpago;
    private javax.swing.JMenuItem subhistorialpagos;
    private javax.swing.JMenuItem submantenimiento;
    private javax.swing.JMenuItem subverservicio;
    private javax.swing.JMenu verservicio;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the usuario
     */
    public UsuarioBean getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(UsuarioBean usuario) {
        this.usuario = usuario;
    }
}
